/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ocean.rtb.persist.bean.thrift.common;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum RtbSrcType implements org.apache.thrift.TEnum {
  SrcTypeSelf(0),
  SrcTypeThird(1);

  private final int value;

  private RtbSrcType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RtbSrcType findByValue(int value) { 
    switch (value) {
      case 0:
        return SrcTypeSelf;
      case 1:
        return SrcTypeThird;
      default:
        return null;
    }
  }
}
